# Generated by Django 3.2.6 on 2021-08-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='image',
            field=models.FileField(upload_to='download/'),
        ),
    ]
