# Generated by Django 3.1 on 2021-08-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='partner/')),
                ('quote', models.TextField(max_length=700)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_nm',
            field=models.CharField(max_length=20),
        ),
    ]
