# Generated by Django 3.1 on 2021-08-08 15:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_service_dtl_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_dtl',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='services/'),
        ),
    ]
